# -*- coding: utf-8 -*-
"""ÁnalisisDeDatos1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLiKXpdYbMREIlbBKqwdadwmIFDGGLb4
"""

# importamos lo requerido
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import lagrange

# valores en el eje x
x = [0,20,40,60,80]
# valores en el eje y
y = [1.792,1.003,0.653,0.467,0.355]

# graficamos
plt.plot(x, y, "x", mew = 2)

# nombreamos la recta x
plt.xlabel('Temperatura (°C)')
# nombreamos la recta y
plt.ylabel('Viscosidad Dinamica (kg/ms)*10^3')

# titulo
plt.title('Temperatura vs Viscosidad dinamica')

# mostramos la funcion
plt.show()

#realizamos el lagrange con los datos obtenidos
p = lagrange(x,y)
#generamos una cantidad de números espaciados uniformemente durante un intervalo de 0 a 80.
x1= np.linspace(0,80)
#evaluo cada numero obtenido
y1=p(x1)
#graficamos
plt.plot(x1,y1, label= 'interpolacion')
plt.plot(x, y, "x", mew = 2, label = "Datos")
plt.legend()

# nombreamos la recta x
plt.xlabel('Temperatura (°C)')
# nombreamos la recta y
plt.ylabel('Viscosidad Dinamica (kg/ms)*10^3')
#titulo del grafico
plt.title('Temperatura vs Viscosidad dinamica')

print('La viscosidad para 50°C corresponde a:', p(50))

#rango desde 0 a 85 sin considerar el 85, ya que va de 5 en 5
for i in range(0,85,5):
  x2 = i
  y2 = p(x2)
  print(x2, y2)

